name: CI-CD

on:
  push: 
    branches: ["main"]
  workflow_dispatch: 
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Retrive project
        uses: actions/checkout@v4.2.2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            rdqueriqueli/conversao-distancia:latest
            rdqueriqueli/conversao-distancia:v${{github.run_number}}

        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Retrive project
        uses: actions/checkout@v4.2.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Configurar o kubectl
        run: echo "Executing o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando Kubectl apply"
